# Generated by Django 4.1.3 on 2022-11-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sections',
            field=models.ManyToManyField(to='core.section'),
        ),
    ]
