# Generated by Django 4.0.8 on 2022-11-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.ManyToManyField(to='core.semester'),
        ),
    ]
