# Generated by Django 4.1.5 on 2023-01-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_teacher_courses_remove_teacher_sections_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
    ]
