# Generated by Django 4.1.5 on 2023-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_student_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parent_phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
