# Generated by Django 4.0.8 on 2022-11-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_sem_student_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
    ]
