# Generated by Django 4.1.3 on 2022-12-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(default=11012001, max_length=50),
            preserve_default=False,
        ),
    ]
