# Generated by Django 4.1.5 on 2023-01-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_student_parent_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e1", models.SmallIntegerField(blank=True, null=True)),
                ("e2", models.SmallIntegerField(blank=True, null=True)),
                ("e3", models.SmallIntegerField(blank=True, null=True)),
                ("e4", models.SmallIntegerField(blank=True, null=True)),
                ("e5", models.SmallIntegerField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
        ),
    ]
