# Generated by Django 4.1.5 on 2023-01-03 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cie"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hod",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignedclasses",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
