# Generated by Django 4.1.5 on 2023-01-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_attendancerecord_date_delete_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_short_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("dept_full_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_hod",
        ),
        migrations.AddField(
            model_name="course",
            name="course_dept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="dept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="dept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
            ),
        ),
    ]
