# Generated by Django 4.1.5 on 2023-01-05 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_department_remove_user_is_hod_course_course_dept_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="dept",
        ),
        migrations.AddField(
            model_name="department",
            name="hod",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
