# Generated by Django 4.1.5 on 2023-01-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_student_dept_department_hod"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hod",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
