# Generated by Django 4.1.5 on 2023-01-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_user_is_hod_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="cie",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.section",
            ),
        ),
    ]
