# Generated by Django 4.1.5 on 2023-01-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_cie_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Staff"},
        ),
        migrations.RemoveField(
            model_name="cie",
            name="e4",
        ),
        migrations.RemoveField(
            model_name="cie",
            name="e5",
        ),
    ]
